services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    restart: "no"
    networks:
      - shared-network

  auth-db:
    restart: "no"
    networks:
      - shared-network

networks:
  shared-network:
    external: true